WebApplication2/Controllers/ComandController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class ComandController : Controller
    {
        static List<Comands> comands;

        public ComandController()
        {
            comands = new List<Comands>()
            {
                new Comands() { Id = 100, Date=1968, Name = "дніпропетровське «Дніпро»" },
                new Comands() { Id = 103, Date=1973, Name = "київського «Динамо»" },
                new Comands() { Id = 130, Date=2000, Name = "збірну України"}
            };
        }
        public IActionResult Index()
        {
            return View(comands);
        }
    }
}

WebApplication2/Controllers/DoctorsController.cs
using AutoMapper;
using Core.Dtos;
using Core.Interfaces;
using Core.Services;
using Data.Data;
using Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Models;
using WebApplication2.SeedExtensions;

namespace WebApplication2.Controllers
{
    [Authorize (Roles = Roles.ADMIN)]
    public class DoctorsController : Controller
    {
       // static List<Doctor>  doctor;
           //private HospitalDbContext ctx = new HospitalDbContext();
        private readonly IMapper mapper;
        private readonly HospitalDbContext ctx;
        private readonly IFileServices fileServices;
        public DoctorsController(IMapper mapper, HospitalDbContext hospitalDbContext, IFileServices fileServices) {
            this.mapper = mapper;
            this.ctx = hospitalDbContext;
            this.fileServices = fileServices;
            //doctor = new List<Doctor>() {
            //    new Doctor() {Id = 1, FirstName ="Grec", Name = "Stepan", LastName = "Ivanivuch" , Birthday = new DateTime(1985,05,01), Categori = "LOR", Work_experience =5},
            //    new Doctor() {Id = 1, FirstName ="Ivanov", Name = "Stanislav", LastName = "Ivanivuch" , Birthday = new DateTime(1988,11,12), Categori = "TERAPEVT", Work_experience =6},
            //    new Doctor() {Id = 1, FirstName ="Sidorov", Name = "Sergii", LastName = "Romanovich" , Birthday = new DateTime(1981,06,25), Categori = "SURGEON", Work_experience =10},
            //    };
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            var doctors = ctx.Doctors
                .Include(x => x.Category)
                .Where(x => !x.Archived)
                .ToList();
            return View(mapper.Map<List<DoctorDto>>(doctors));
        }

        public IActionResult Archive()
        {
            // .. load data from database ..
            var doctors = ctx.Doctors
                .Include(x => x.Category) // LEFT JOIN
                .Where(x => x.Archived)
                .ToList();

            return View(mapper.Map<List<DoctorDto>>(doctors));
        }

        // GET: 
        [HttpGet]
        public IActionResult Create()
        {
            // ViewBag.PropertyName = value;
            ViewBag.Categories = new SelectList(ctx.Categories.ToList(), "Id", "Name");
            //LoadCategories();
            ViewBag.CreateMode = true;

            return View("Upsert");
        }

        
        // POST
        [HttpPost]
        public async Task<IActionResult> Create(DoctorDto model)
        {
            // TODO: add data validation
            if (!ModelState.IsValid)
            {
                ViewBag.CreateMode = false;
                LoadCategories();
                return View("Upsert", model);
            }
            
            var entyti = mapper.Map<Doctor>(model);
            entyti.ImageUrl = await fileServices.SaveDoctorImage(model.Image);

          
            ctx.Doctors.Add(entyti);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }




        [HttpGet]
        public IActionResult Edit(int id)
        {
            var doctors = ctx.Doctors.Find(id);

            if (doctors == null) return NotFound();

            LoadCategories();
            ViewBag.CreateMode = false;
            return View("Upsert", mapper.Map<DoctorDto>(doctors));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DoctorDto model)
        {
            // TODO: add data validation
            if (!ModelState.IsValid)
            {
                ViewBag.CreateMode = false;
                LoadCategories();
                return View("Upsert", model);
            }
            if (model.Image != null)
            {
                model.ImageUrl = await fileServices.EditDoctorImage(model.ImageUrl, model.Image);
            }
            ctx.Doctors.Update(mapper.Map<Doctor>(model));
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }










        public async Task<IActionResult> Delete(int id)
        {
            var doctors = ctx.Doctors.Find(id);

            if (doctors == null) return NotFound();
            await fileServices.DeleteDoctorImage(doctors.ImageUrl);

            ctx.Doctors.Remove(doctors);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult ArchiveItem(int id)
        {
            var doctors = ctx.Doctors.Find(id);

            if (doctors == null) return NotFound();

            doctors.Archived = true;

            ctx.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult RestoreItem(int id)
        {
            var doctors = ctx.Doctors.Find(id);

            if (doctors == null) return NotFound();

            doctors.Archived = false;
            ctx.SaveChanges();

            return RedirectToAction("Archive");
        }
        private void LoadCategories()
        {
            // ViewBag.PropertyName = value;
            ViewBag.Categories = new SelectList(ctx.Categories.ToList(), "Id", "Name");
        }
    }
}

WebApplication2/Controllers/OrdersController.cs
using AutoMapper;
using Core.Dtos;
using Core.Interfaces;
using Core.Services;
using Data.Data;
using Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace WebApplication2.Controllers
{
    //public class OrdersController : Controller
    //{
    //}
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrdersServices ordersService;
        private readonly IMapper mapper;
        private readonly HospitalDbContext context;
        private readonly RoleManager<IdentityRole> userManager;
        private string UserId => User.FindFirstValue(ClaimTypes.NameIdentifier)!;

        public OrdersController(IOrdersServices ordersService, IMapper mapper, HospitalDbContext context)
        {
            this.ordersService = ordersService;
            this.mapper = mapper;
            this.context = context;
            // this.userManager = userManager;
        }
        public IActionResult Index()
        {
            // userManager.CreateAsync(new IdentityRole());
            //var doctor = context.Doctors;
            //.Include(x => x.Category)
            //.ToList();
            //return View(mapper.Map<List<DoctorDto>>(doctor));
            return View(ordersService.GetOrders(UserId));
        }

        public IActionResult Create(int doctorId)
        {
            ordersService.Create(UserId, doctorId);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApplication2/Views/Shared/_DoctorHomeCardPartial.cshtml
@model DoctorDto

<div class="col">
    <div class="card h-100">
        <img height="130" src="@Model.ImageUrl" class="card-img-top" alt="@Model.Name">
        <div class="card-body">
            <h5 class="card-title">
                <a asp-controller="Doctors" asp-action="Details" asp-route-id="@Model.Id">@Model.Name</a>
            </h5>
            <p class="card-text">
                @Model.CategoryName?<br />
                @* Left: @Model.Quantity *@
            </p>
            <a asp-controller="Orders" asp-action="Create" asp-route-doctorId="@Model.Id" class="btn btn-success mt-3">Confirm</a>
@*            <a asp-controller="Doctors" asp-action="Add" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.Path" class="btn btn-primary">Add to Cart</a>
 *@        </div>
       @*  <div class="card-footer">
            <small class="text-muted">
                Price: <span class="badge bg-secondary">@Model.Price$</span>
            </small>
        </div> *@
    </div>
</div>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <img alt="Logo" height="90" src="https://dobrobut.com/images/logo.svg" width="250" data-v-9ba48d6e="">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Biography">Biography</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Life">way of life</a>
                        </li>
                        <li class="nav-item">

                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Fact">10 fact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comand" asp-action="Index">comand</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctors" asp-action="Index">doctor</a>
                        </li>
                            
                        }
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li> *@
                    </ul>


                    <ul class="navbar-nav">
                        <partial name="_LoginPartial.cshtml" />

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-basket2"></i>
                                @* Cart (@cartService.GetCount()) *@
                            </a>
                        </li>
                    </ul>



                  @*   <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login  <i class="bi bi-person-add"></i> </a>
                           
                        </li>
                    </ul> *@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>